server:
  port: 8081
spring:
  application:
    name: consumer-helloworld-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instanace:
    prefer-ip-address: true
